### ISSUE TITLE
send_op_return not present on PrivateKeyTestnet

### ISSUE THREAD

**Issue by joshua-s** [AustEcon/bitsv#22]
When I attempt to use `send_op_return()` on a `PrivateKeyTestnet` key, I get an `AttributeError`.

**Comment by AustEcon** [comment]
Yeah not added yet. 
Are you operational though for the hackathon in the meantime?

Just needs to be connected PrivateKeyTest up to NetworkAPI.

Which in turn should call BitIndex3 api testnet.

**Comment by joshua-s** [comment]
I am operational, thanks!

**Comment by AustEcon** [comment]
I also noticed during the hackathon that this function had the very annoying property of consolidating all of my utxos! I am in the process of remedying this!
- I have noticed a lot of things that need improving from the hackathon...

**Comment by AustEcon** [comment]
Added in #25
