### ISSUE TITLE
Avoid generate a uxto with value less than dust (546)

### ISSUE THREAD

**Issue by carpemer** [AustEcon/bitsv#27]
https://github.com/AustEcon/bitsv/blob/master/bitsv/transaction.py#L200

The problem is when the balance(A) is 1000 and you want to send 600 to someone(B), and the calculated fee is 300, then the code will generate the tx like this:
Input A: 1000
Output B:600, A100
(implicit) Fee: 300

Then bitindex will generate a tx for you and broadcast it, but this tx will not be accepted by any miner, because a uxto with a value less than dust is not accepted.

One possible solution is to move all 400 to the miner. 
Input A: 1000
Output B:600
(implicit) Fee: 400

This only applies to the case when the remnant < dust(546), if the remnant is > dust, there will be no effect.

Of course, we could adjust this in the future once the new agreement reached for most of the SV miner.
https://www.reddit.com/r/bitcoincashSV/comments/abj9nb/bitcoin_needs_to_completely_remove_the_dust/

How about your guys opinion? @AustEcon @joshua-s @teran-mckinney

**Comment by teran-mckinney** [comment]
Ah, yes. Dust. This is interesting. Some wallets won't let you make an output less than the dust limit.

I think the SV way would have miners set dust. But some kind of dust_avoid or dust_eat behavior could be good, even if we eventually set it to 0.

**Comment by AustEcon** [comment]
Great work on this @carpemer and @teran-mckinney in #26 - looking good.
