### ISSUE TITLE
send() can not work even with get_balance > 1000

### ISSUE THREAD

**Issue by carpemer** [AustEcon/bitsv#3]
&gt; k.get_balance()
'7216'
&gt; to=[('1GrFgWWadFMyB3a2aCp27vLD33i3oCSsEK',1000, 'satoshi')]
&gt; k.get_unspents()
[Unspent(amount=7216, confirmations=148, script='76a914bad4871d5bdeabb087f23a04f8342c31248c23ed88ac', txid='77b999b91631ae580dcd73046b228c9769eff54465faed7d0f8fd1c1446c680c', txindex=0)]
&gt; k.send(to)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/bitsv/wallet.py", line 295, in send
    outputs, fee=fee, leftover=leftover, combine=combine, message=message, unspents=unspents
  File "/usr/local/lib/python3.6/site-packages/bitsv/wallet.py", line 253, in create_transaction
    custom_pushdata=custom_pushdata
  File "/usr/local/lib/python3.6/site-packages/bitsv/transaction.py", line 147, in sanitize_tx_data
    raise ValueError('Transactions must have at least one unspent.')
ValueError: Transactions must have at least one unspent.

This address has balance, the uxto tx has > 1 confirmation, but it never successfully send the bsv to other address. 
Is there someone else has a similar experience like this?

**Comment by AustEcon** [comment]
I will look into this tomorrow.

As discussed in DM (for the benefit of outside observers):
I've had this issue before but didn't get to the bottom of it... My intuition is that it is something to do with retrieving the UTXOs from the APIs (the non-BitIndex ones) and I wonder if they get out of sync or something (e.g. trying to use old / used UTXOs) ... I'll look into it... 

I do NOT retrieve UTXOs from BitIndex - only use BitIndex for sending...
The fix may involve finding a way to retrieve the updated UTXOs from a better (faster) source...

**Comment by AustEcon** [comment]
Okay - I have rigged up BitIndex now as the API that is used for getting balance, utxos and for broadcasting.

I have only done haphazard, rudimentary testing but it seems to be working well.
I've sent some 1000 byte op_returns in quick succession and they all appear on _unwriter's babel immediately with no trouble.

Feedback as to your experience would be good.

If all seems to be in working order I can look to putting out the updated release (version 0.5.4) in a couple of days with the 100kb op_return bug fixed + BitIndex API rigged up properly for reliability.

**Comment by carpemer** [comment]
Tested some simple use cases, it works now.
Could we call the get_unspents() in the send() just like send_op_return(), so that we could call send() multi-times in sequence.

**Comment by AustEcon** [comment]
Oh yep. No problem.
Will have to wait till after work tomorrow though. 
Pull requests are welcome though too. :)

**Comment by AustEcon** [comment]
Thank you for the PR - I will close this issue now.
