### ISSUE TITLE
Printing to stdout on network retries

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#38]
https://github.com/AustEcon/bitsv/blob/master/bitsv/network/services/network.py#L57

Never, ever should a library print to stdout unless asked to. We can change this to write to stderr. We can remove it. Or we can just do logging.warning and let the upstream logging setup handle it. We can also change the default logging level. All of these are fine.

Also, Bitindex is down, again.

`ConnectionError: All APIs are unreachable, exception:504 Server Error: Gateway Time-out for url: https://api.bitindex.network/api/v3/main/addrs/utxo`

Been down for a few hours now. Do you have external monitoring in place?

**Comment by teran-mckinney** [comment]
I'm sorry for the tone. I'm a systems guy so this stuff bothers me more than it does most. If you need help with it, just let me know. I rely on this code in production so it's important for me that it works. Happy to help here in this library, with Bitindex, add in other APIs, whatever.

**Comment by joshua-s** [comment]
@teran-mckinney Nice catch. I'd prefer allowing upstream logging to handle this unless there is a pertinent use case that would necessitate this function to accept a `logger` argument and follow this additional logic.

**Comment by AustEcon** [comment]
Ah sorry. Yeah that's not good.
I concur with the preference for logging.
I think you merged this though @teran-mckinney in #26! 😝 So maybe there's a little blame for both of us? 😛.
As far as BitIndex being down on mainnet... I have a Whatsonchain API already setup (and available from pypi - https://github.com/AustEcon/whatsonchain) but I am waiting on them to add "confirmations" to the utxo response... until then it is no use wiring it up... I did contact them and they said that it's now on their to-do list...

**Comment by AustEcon** [comment]
https://bchsvexplorer.com/api/addr/ is a possibility (just for mainnet)... I'm pretty sure I have the code for that lying around somewhere... if I find it, I'll drop it in and do a PR.

**Comment by teran-mckinney** [comment]
Yeah, completely my fault, I should have caught it. I think I'm being careful sometmes with reviews when really I might not be.

Thank you!

BitIndex is back, too.

**Comment by AustEcon** [comment]
No I actually saw it and thought "oh that's weird!... " and then stupidly continued on my merry way... 🙄

Yes BitIndex got DDOS attacked if you didn't know. See: https://twitter.com/MatterCloud/status/1152660923448025089?s=20

**Comment by AustEcon** [comment]
Closing this issue. Fixed in #42
