### ISSUE TITLE
Add get_unspent() back to NetworkAPI

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#40]
Looks like we renamed get_unspent() to get_unspents() recently. Would be nice to have a wrapper function with the same name for backwards compatibility.

**Comment by joshua-s** [comment]
PR here: #41

**Comment by teran-mckinney** [comment]
Fantastic, thank you!

**Comment by teran-mckinney** [comment]
Looking into this more, this isn't such a big deal because it's changed anyways. Even with your change we can't call `get_unspent()`. We have to call NetworkAPI as a function.

This is what I used in walkingliberty and forgot about:

https://github.com/teran-mckinney/walkingliberty-python/blob/c3e6f5ef4e706b985d3599f1565841434cbe80a0/walkingliberty/__init__.py#L95

I'm sorry, I should have seen this sooner.

**Comment by teran-mckinney** [comment]
Here's what I ended up doing: https://github.com/teran-mckinney/bitcoinacceptor-python/commit/aedaeca2fd9dd317d2b283ee9b5d92c20b266f8b#diff-909255c8a6a005a80830665fa8d8f931R103

I think since this is non-trivial it's best to move forward with it as-is.

Thank you again, Josh!

**Comment by joshua-s** [comment]
Sounds good. It would be very messy to keep backwards compatibility from before the NetworkAPIs needed to be instantiated.

**Comment by teran-mckinney** [comment]
Yeah, that's for sure. I was thinking that just the function was renamed but that's certainly not all here.

**Comment by AustEcon** [comment]
Why not just add an alias of 
"get_unspent = get_unspents"???

**Comment by AustEcon** [comment]
Yes the big change is NetworkAPI instantiation. But other than that could just have an alias:
"self.get_unspent = self.get_unspents

**Comment by teran-mckinney** [comment]
That isn't the only issue. With bit/bitcash, you call `bit.network.NetworkAPI.get_unspent(address)`. With bitsv you have to call `bit.network.NetworkAPI('main').get_unspents(address)`

So even if it were just `get_unspent()`, you still have to treat NetworkAPI as a class or what not.

**Comment by AustEcon** [comment]
Yes, that's the big change.

**Comment by teran-mckinney** [comment]
Yup! I understand, it makes sense. It was a nice change on the whole, for sure.
