### ISSUE TITLE
Fix get_utxos() in https://github.com/AustEcon/whatsonchain

### ISSUE THREAD

**Issue by AustEcon** [AustEcon/bitsv#46]
I think it will not be too difficult to fix up whatsonchain such that it returns the number of confirmations and can therefore be compatible with bitsv's Unspents dataclass.

As per previous discussion...https://github.com/AustEcon/bitsv/pull/39#issuecomment-513504148

I think 2 function calls should be acceptable for this purpose...
One to get current block height and another for the utxos --> calculate number of confirmations.

Once this is fixed we can **finally** add whatsonchain to main / test and stn as a second-line API for redundancy. Which I see as quite important.

**Comment by teran-mckinney** [comment]
That would be nice to have, for sure.

**Comment by AustEcon** [comment]
Fixed this ages ago in https://github.com/austecon/bitsv/commit/06013a7750d1e26e3198d09009fa9607b5668120

See `WhatsonchainNormalised`
