### ISSUE TITLE
To Do list

### ISSUE THREAD

**Issue by AustEcon** [AustEcon/bitsv#5]
- [x] Add Hierarchical Deterministic key support for priv, xpub --> generation of electrum sv and handcash wallet public / private key pairs (derivation path m/0')
- [ ] Create a separate HandCash api powered by bitsv in a separate repo.
- [ ] Create functions for posting of images / media etc. to blockchain (e.g. bitpaste compatible way)
- [x] Add in BitIndex xpub related queries
- [x] BitIndex3 added by Joshua-S
- [x] Fix tests
- [x] Fix testnet
- [x] Tidy up final re-branding and documentation 
- [x] Add "confirmations" field to unspents so 0-conf balance versus 1-conf etc. balance can be calculated (may need to contact BitIndex)

Edit 12/04/19 Please comment below with a wishlist of features you want added and I will endeavour to provide! Or recruit help! Donations gratefully received! 

Or if any of the above features are important to you... let me know so I can gauge if my time will actually be well spent there.

**Comment by joshua-s** [comment]
It would be great if there could be regtest support.

**Comment by teran-mckinney** [comment]
Tests seem to be passing at the moment.

**Comment by AustEcon** [comment]
@joshua-s It does have a test module. Currently at 87% coverage. Click on the little button on the ReadMe page that says "coverage 87%"

**Comment by joshua-s** [comment]
Thanks for the info. I was actually referring to "Regtest" as in the local testing environment for BSV.

If I understand that properly, it will allow me to develop blockchain applications without paying any fees and without publishing the transactions on a public chain. I suppose testnet support would work as well, but with the caveat of making my dev data public.

If there is something I am missing, please advise.

**Comment by joshua-s** [comment]
@teran-mckinney @AustEcon Thanks for the info. I was actually referring to "Regtest" as in the local testing environment for BSV.

If I understand that properly, it will allow me to develop blockchain applications without paying any fees and without publishing the transactions on a public chain. I suppose testnet support would work as well, but with the caveat of making my dev data public.

If there is something I am missing, please advise.

**Comment by AustEcon** [comment]
Ah! Okay. I wasn't aware of that. Thanks. 

I plan on connecting up testnet as soon as I can. (Or if someone else submits a PR).

I imagine "RegTest" should be very similar to implement in theory?
