### ISSUE TITLE
Add sendall() function to PrivateKey class

### ISSUE THREAD

**Issue by AustEcon** [AustEcon/bitsv#50]
Currently the way to 'sendall' to an address is to do:
`my_key.send([], leftover='ADDRESS_TO SENDALL_TO')`

Which basically passes in an empty list for outputs and sends all of the remaining change (everything) to the desired address. This is not intuitive to figure this out though and could be described as a bit of a "hack". 

I therefore propose adding a sendall() to PrivateKey class so that syntax can be:
`my_key.sendall('ADDRESS_TO SENDALL_TO')`

**Comment by teran-mckinney** [comment]
In my opinion, if we add this it should be called sweep.

**Comment by joshua-s** [comment]
@AustEcon what about just setting a boolean flag `send_all=True`?

**Comment by AustEcon** [comment]
I don't have strong feelings about it. That would work just fine too. 

If 'sweep' is the more correct terminology then I guess we should go with that. Needs to have an unambiguous docstring explaining what it does - wouldn't be a very nice surprise...

Would it be very intuitive though to use these boolean flags? Because basically you would still need to provide an address and an amount as a list of tuples... then sweep will...?send the rest there? (but what if you have different addresses in that list... which one??).

This is the reason that (for something that could give someone a pretty bad day if it does this when they don't want it to) - I favour a specialised function. Put in the address and everything gets sent to there.
