### ISSUE TITLE
Support miner fee less than 1 sat/b

### ISSUE THREAD

**Issue by gitzhou** [AustEcon/bitsv#56]
Hi Aust, per our conversation in Slack, raise this issue as a reminder.

![](https://aaron67-public.oss-cn-beijing.aliyuncs.com/20191029153359.png)

Thanks.

**Comment by AustEcon** [comment]
Thanks. Let's see what we can do for one of the next releases 😉

**Comment by gitzhou** [comment]
Close refer to #63
