### ISSUE TITLE
Unable to pushtx over Tor

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#57]
Seems like Bitindex3 may not be working. bchsvexplorer.com has Cloudflare and isn't configured to not block Tor.

**Comment by teran-mckinney** [comment]
Bitindex3 Testnet is buggy, our tests are failing. I contacted them.

Don't know who runs bchsvexplorer.com, but I emailed the technical contact on the whois through Godaddy.

**Comment by teran-mckinney** [comment]
Bitindex3 pushtx seemed to just come back. I didn't get any logs from it but maybe they addressed it already.

**Comment by AustEcon** [comment]
Is this settled now with our main API back online?

**Comment by atteeela** [comment]
Yes, it is

**Comment by teran-mckinney** [comment]
Thank you!
