### ISSUE TITLE
BitIndex is now MatterCloud and requires API keys

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#65]
Even a basic call like this fails.

https://api.bitindex.network/api/v3/main/addr/17msuwJxJoQKfH7197VvLRA3xzVDGNZqUT

**Comment by AustEcon** [comment]
Righto. It's 3am here. Will get right on it when I get a spare moment ;) 

Don't wait up for me though if you want to merge that PR or implement whatever you think needs done 👍

**Comment by teran-mckinney** [comment]
Ok, thank you! Another API is working for me so it's okay for the moment.
