### ISSUE TITLE
Mattercloud is now a paid service

### ISSUE THREAD

**Issue by AustEcon** [AustEcon/bitsv#68]
As Mattercloud is now a paid service and our tests are failing, I think I'll make a simple change that disables use of mattercloud's api in the absence of an environment variable:
`MATTERCLOUD_API_KEY`

We could add that to our Travis CI later on if we want to I believe.

It would be up to application developers to set this environment variable prior to launch which would activate mattercloud's api and use it as the highest priority API.

Any objections to this methodology?
Sound alright @MatterCloud?

**Comment by teran-mckinney** [comment]
I like that idea.
