### ISSUE TITLE
`black` the codebase

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#70]
https://github.com/psf/black

What do you think about doing this for bitsv? Obviously should be a single commit with nothing else going on that commit.

**Comment by teran-mckinney** [comment]
@AustEcon, could you take a look at this?

**Comment by AustEcon** [comment]
It seems pretty cool but without having used it before feels like it could be a bit of a pita to get used to initially... and doesn't feel like bitsv is in desperate need of something like this for such a small project - that's my initial feeling. 

If I were already familiar with it and using it regularly then maybe I would want it.

**Comment by teran-mckinney** [comment]
Gotcha, that is far. I've been working on it for bit and bitcash. There is one string formatting issue that seems to need to be fixed afterwards.

After using `go fmt` a lot, I like the idea. Pretty handy especially when I'm using `vi` without any plugins or the like.
