### ISSUE TITLE
prepare_transaction needs the key object

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [AustEcon/bitsv#73]
Hi. as I read in [bitsv documentation](https://austecon.github.io/bitsv/guide/advanced.html#offline-transactions) I need to call the prepare transaction when I'm online to prepare a transaction and then I can sign this transaction offline. logically the prepare_tranaction function shouldn't need the key object to work. but when I run the `tx_data = PrivateKey.prepare_transaction(address=sender.address, outputs=[(receiver.address, amountToSpend , 'bsv')])` I get this error :
TypeError: prepare_transaction() missing 1 required positional argument: 'self'

 I checked the wallet.py file of bitsv and recognized that prepare_transaction isn't a @classmethod while it should be!

**Comment by AustEcon** [comment]
Ah yes. Sounds about right. Thanks for the concise report.

Will patch this when I get a moment. 😉

**Comment by AustEcon** [comment]
Will this do okay? I had to change the function signature to to add the 'network' positional arg... so this will technically be a breaking change but I'm not aware of too many people using this functionality... 
![image](https://user-images.githubusercontent.com/8123976/98430058-af0ca680-210f-11eb-9e0a-6eed0c4d909f.png)

**Comment by AustEcon** [comment]
Cut new release now. Will close this issue. LMK though of any issues and can reopen as needed.
