### ISSUE TITLE
Can't create transaction or get balance on bsv testnet

### ISSUE THREAD

**Issue by Liorvais1** [AustEcon/bitsv#80]
seems like whatsonchain is down. 
For example when I try to get balance request to: https://api.whatsonchain.com/v1/bsv/test/chain/info
takes too long, eventually gets a timeout error.

**Comment by AustEcon** [comment]
yeah. Looks like testnet api is down. but mainnet is okay

**Comment by AustEcon** [comment]
I've pinged the whatsonchain telegram. See what they say. 

Whatsonchain has historically been the most reliable of the APIs so I imagine it will be back online soon enough.

**Comment by AustEcon** [comment]
If you're in a pinch... It's been a while since I tested it... but you could try the MATTERCLOUD_API_KEY=<your api key for mattercloud> as an environment variable to activate mattercloud's api.

It doesn't have test coverage though so cannot guarantee it working...

**Comment by AustEcon** [comment]
Working now. Mo has sorted it already 😉
